pipeline {
    agent any

    stages {
        stage('GIT Checkout') {
            steps {
                echo '*********Git checkout code*********'
                git branch: 'master',
                        credentialsId: 'GitHub_643',
                        url: 'https://github.com/vdinuu/PlaywrightJS_AllureFramework.git'
            }
        }
        stage('Execute test cases') {
            steps {
                echo '*********Executing test cases**********'
                bat '''
                    npm run test
                    '''
            }
        }
        stage('Publish HTML Report') {
            steps {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'allure-report', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: '', useWrapperFileDirectly: true])
            }
        }
    }
}
