pipeline {
    agent any

    parameters {
        choice(name: 'Browser', choices: ['chromium', 'firefox', 'webkit'], description: "Select the browser to be used for test execution")
//        string(name: 'TAG', defaultValue: "AddPlace", description: 'Enter the tag you want to use for execution')
    }

    stages {
        stage('GIT Checkout') {
            steps {
                echo '*********Git checkout code*********'
                git branch: 'master',
                        credentialsId: 'GitHub_643',
                        url: 'https://github.com/vdinuu/PlaywrightJS_AllureFramework.git'
            }
        }
        stage('Execute test cases') {
            steps {
                echo '*********Executing test cases**********'
                bat '''
                    npm run test:${params.Browser}
                    '''
            }
        }
        stage('Publish HTML Report') {
            steps {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'allure-report', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: '', useWrapperFileDirectly: true])
            }
        }
    }
}
